################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_conv_f32.c \
../Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Core/Src/Source/FilteringFunctions/arm_conv_q15.c \
../Core/Src/Source/FilteringFunctions/arm_conv_q31.c \
../Core/Src/Source/FilteringFunctions/arm_conv_q7.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_f16.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_f32.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_f64.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_q15.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_q31.c \
../Core/Src/Source/FilteringFunctions/arm_correlate_q7.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_f16.c \
../Core/Src/Source/FilteringFunctions/arm_fir_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_f64.c \
../Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_init_f16.c \
../Core/Src/Source/FilteringFunctions/arm_fir_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_init_f64.c \
../Core/Src/Source/FilteringFunctions/arm_fir_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_init_q7.c \
../Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_q7.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../Core/Src/Source/FilteringFunctions/arm_lms_f32.c \
../Core/Src/Source/FilteringFunctions/arm_lms_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_lms_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_lms_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Core/Src/Source/FilteringFunctions/arm_lms_q15.c \
../Core/Src/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_conv_f32.o \
./Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Core/Src/Source/FilteringFunctions/arm_conv_q15.o \
./Core/Src/Source/FilteringFunctions/arm_conv_q31.o \
./Core/Src/Source/FilteringFunctions/arm_conv_q7.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_f16.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_f32.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_f64.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_q15.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_q31.o \
./Core/Src/Source/FilteringFunctions/arm_correlate_q7.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_f16.o \
./Core/Src/Source/FilteringFunctions/arm_fir_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_f64.o \
./Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_init_f16.o \
./Core/Src/Source/FilteringFunctions/arm_fir_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_init_f64.o \
./Core/Src/Source/FilteringFunctions/arm_fir_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_init_q7.o \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_q7.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./Core/Src/Source/FilteringFunctions/arm_lms_f32.o \
./Core/Src/Source/FilteringFunctions/arm_lms_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_lms_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_lms_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Core/Src/Source/FilteringFunctions/arm_lms_q15.o \
./Core/Src/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_conv_f32.d \
./Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Core/Src/Source/FilteringFunctions/arm_conv_q15.d \
./Core/Src/Source/FilteringFunctions/arm_conv_q31.d \
./Core/Src/Source/FilteringFunctions/arm_conv_q7.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_f16.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_f32.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_f64.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_q15.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_q31.d \
./Core/Src/Source/FilteringFunctions/arm_correlate_q7.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_f16.d \
./Core/Src/Source/FilteringFunctions/arm_fir_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_f64.d \
./Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_init_f16.d \
./Core/Src/Source/FilteringFunctions/arm_fir_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_init_f64.d \
./Core/Src/Source/FilteringFunctions/arm_fir_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_init_q7.d \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_q7.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./Core/Src/Source/FilteringFunctions/arm_lms_f32.d \
./Core/Src/Source/FilteringFunctions/arm_lms_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_lms_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_lms_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Core/Src/Source/FilteringFunctions/arm_lms_q15.d \
./Core/Src/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/Source/FilteringFunctions/%.o Core/Src/Source/FilteringFunctions/%.su Core/Src/Source/FilteringFunctions/%.cyclo: ../Core/Src/Source/FilteringFunctions/%.c Core/Src/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../Core/Inc -I"C:/Users/bonfi/Downloads/STM_Projects/DSP_Trial/Core/Inc/PrivateInclude" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bonfi/Downloads/STM_Projects/DSP_Trial/Core/Inc/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-Src-2f-Source-2f-FilteringFunctions

clean-Core-2f-Src-2f-Source-2f-FilteringFunctions:
	-$(RM) ./Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.d ./Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.o ./Core/Src/Source/FilteringFunctions/FilteringFunctionsF16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su
	-$(RM) ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_conv_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_f32.d ./Core/Src/Source/FilteringFunctions/arm_conv_f32.o ./Core/Src/Source/FilteringFunctions/arm_conv_f32.su ./Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.d ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.o ./Core/Src/Source/FilteringFunctions/arm_conv_fast_q31.su ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.d ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.o ./Core/Src/Source/FilteringFunctions/arm_conv_opt_q7.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_f32.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q31.su ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.d ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.o ./Core/Src/Source/FilteringFunctions/arm_conv_partial_q7.su ./Core/Src/Source/FilteringFunctions/arm_conv_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_q15.d ./Core/Src/Source/FilteringFunctions/arm_conv_q15.o ./Core/Src/Source/FilteringFunctions/arm_conv_q15.su ./Core/Src/Source/FilteringFunctions/arm_conv_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_q31.d ./Core/Src/Source/FilteringFunctions/arm_conv_q31.o ./Core/Src/Source/FilteringFunctions/arm_conv_q31.su ./Core/Src/Source/FilteringFunctions/arm_conv_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_conv_q7.d ./Core/Src/Source/FilteringFunctions/arm_conv_q7.o ./Core/Src/Source/FilteringFunctions/arm_conv_q7.su ./Core/Src/Source/FilteringFunctions/arm_correlate_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_f16.d ./Core/Src/Source/FilteringFunctions/arm_correlate_f16.o ./Core/Src/Source/FilteringFunctions/arm_correlate_f16.su ./Core/Src/Source/FilteringFunctions/arm_correlate_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_f32.d ./Core/Src/Source/FilteringFunctions/arm_correlate_f32.o ./Core/Src/Source/FilteringFunctions/arm_correlate_f32.su ./Core/Src/Source/FilteringFunctions/arm_correlate_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_f64.d ./Core/Src/Source/FilteringFunctions/arm_correlate_f64.o ./Core/Src/Source/FilteringFunctions/arm_correlate_f64.su ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su
	-$(RM) ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.d ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.o ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q15.su ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.d ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.o ./Core/Src/Source/FilteringFunctions/arm_correlate_fast_q31.su ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.d ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.o ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q15.su ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.d ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.o ./Core/Src/Source/FilteringFunctions/arm_correlate_opt_q7.su ./Core/Src/Source/FilteringFunctions/arm_correlate_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_q15.d ./Core/Src/Source/FilteringFunctions/arm_correlate_q15.o ./Core/Src/Source/FilteringFunctions/arm_correlate_q15.su ./Core/Src/Source/FilteringFunctions/arm_correlate_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_q31.d ./Core/Src/Source/FilteringFunctions/arm_correlate_q31.o ./Core/Src/Source/FilteringFunctions/arm_correlate_q31.su ./Core/Src/Source/FilteringFunctions/arm_correlate_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_correlate_q7.d ./Core/Src/Source/FilteringFunctions/arm_correlate_q7.o ./Core/Src/Source/FilteringFunctions/arm_correlate_q7.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_f64.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_f64.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_decimate_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_f16.d ./Core/Src/Source/FilteringFunctions/arm_fir_f16.o ./Core/Src/Source/FilteringFunctions/arm_fir_f16.su ./Core/Src/Source/FilteringFunctions/arm_fir_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_f64.d ./Core/Src/Source/FilteringFunctions/arm_fir_f64.o ./Core/Src/Source/FilteringFunctions/arm_fir_f64.su ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_fast_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_init_f16.d ./Core/Src/Source/FilteringFunctions/arm_fir_init_f16.o ./Core/Src/Source/FilteringFunctions/arm_fir_init_f16.su ./Core/Src/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_init_f64.d ./Core/Src/Source/FilteringFunctions/arm_fir_init_f64.o
	-$(RM) ./Core/Src/Source/FilteringFunctions/arm_fir_init_f64.su ./Core/Src/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_init_q7.d ./Core/Src/Source/FilteringFunctions/arm_fir_init_q7.o ./Core/Src/Source/FilteringFunctions/arm_fir_init_q7.su ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_lattice_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_q7.d ./Core/Src/Source/FilteringFunctions/arm_fir_q7.o ./Core/Src/Source/FilteringFunctions/arm_fir_q7.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q15.su
	-$(RM) ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q31.su ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.d ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.o ./Core/Src/Source/FilteringFunctions/arm_fir_sparse_q7.su ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.d ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.o ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_f32.su ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.d ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.o ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q15.su ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.d ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.o ./Core/Src/Source/FilteringFunctions/arm_iir_lattice_q31.su ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./Core/Src/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./Core/Src/Source/FilteringFunctions/arm_lms_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_f32.d ./Core/Src/Source/FilteringFunctions/arm_lms_f32.o ./Core/Src/Source/FilteringFunctions/arm_lms_f32.su ./Core/Src/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_lms_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_lms_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_lms_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_lms_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_lms_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_lms_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.d ./Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.o ./Core/Src/Source/FilteringFunctions/arm_lms_norm_f32.su ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Core/Src/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.d ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.o ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q15.su ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.d ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.o ./Core/Src/Source/FilteringFunctions/arm_lms_norm_q31.su ./Core/Src/Source/FilteringFunctions/arm_lms_q15.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_q15.d ./Core/Src/Source/FilteringFunctions/arm_lms_q15.o ./Core/Src/Source/FilteringFunctions/arm_lms_q15.su ./Core/Src/Source/FilteringFunctions/arm_lms_q31.cyclo ./Core/Src/Source/FilteringFunctions/arm_lms_q31.d ./Core/Src/Source/FilteringFunctions/arm_lms_q31.o ./Core/Src/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Core-2f-Src-2f-Source-2f-FilteringFunctions

